name: Build & Deploy Web (Production)

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/**'
      - 'packages/shared/**'  # aqui eh preciso a shared pois a web dependete desta.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Deploy
        run: echo "Deployed"